### ISSUE TITLE
Allow arbitrary computation names

### ISSUE THREAD

**Issue by kdund** [XENONnT/alea#115]
https://github.com/XENONnT/alea/blob/bcad6fdaf8b53767360d327f52ad179310c46646/bin/alea-submission#L13

It can be useful to just add some throw-away computations in addition to the main named ones (            "discovery_power", "threshold", "sensitivity", opinions? It should just be a question of throwing a warning rather than an error if another name is used as long as it exists in the run config file.

**Comment by hammannr** [comment]
But if it's defined in the config but not in the submitter/runner it can't do anything sensible or not? Do you maybe have an example of where/how you would like to use it? 😊

**Comment by kdund** [comment]
Sure, lets say you want to do a small set of toyMCs to check something, perhaps you want to make a pull-plot-- you copy one of the current dict entries, change the generate_args and fit parameters to your liking, and then you wish to submit those-- the submission is exactly the same as for "sensitivity"-- what changes is that you perhaps only ask for the "true" fit, and you don't compute confidence intervals. 

Or at least to my knowledge, there is nothing that changes in how toyMCs are run between "discovery power" and "sensitivity"-- it is just the content of the run config dict entry

**Comment by hammannr** [comment]
You're probably right! The only thing which is for sure different is the threshold computation. Then this sounds good to me!
