### ISSUE TITLE
Add Runner class

### ISSUE THREAD

**Issue by dachengx** [XENONnT/alea#16]
it should
1. have a method `toy_simulation`
2. have a method to call `fitting` of `StatisticalModel`
3. have a method `inference_interafce`
4. have a method `run_toy_fit(generate_parameters, fit_parameters, , data)` which call `toy_simulation`

**Comment by kdund** [comment]
Runner must: 
- initialise statistical model (give correct class + any kwargs taken by the init of said class)
- Either call the models generate data, or read in a cached file containing toyMCs. 

for each toy: 
 - generate data or read in cached data. 
 - fit data for all hypotheses (i.e. "free", {}, {"signal_rate_multiplier":3})
 - Compute confidence intervals for one or more hypotheses. 
 - Store fitted parameters and likelihood values to results array
 - optional: store toyMC data to list
THen: 
- output fitted parameters and likelihood values in the inference_interface structure
- optional: store toyMC data list in the inference_interface structure.

**Comment by dachengx** [comment]
what I should not do in the first stage of runner development: 

1. first run runner with the Gaussian model as an example, the later implemented complex statistical model will have the same API as the Gaussian model, so should not read the yaml configuration files
2. also should only care about manipulating the likelihood but not job submitting in the runner, so should not do job submission

**Comment by kdund** [comment]
I think for now, we just stick with the best-fit for the purposes of confidence interval computations being the 0th in the list of hypotheses

**Comment by hammannr** [comment]
List of needed keyword arguments:
- statistical_model
- statistical_model_args
- generate_values
- fit_guesses
- n_mc
- poi (parameter_of_interest)
- hypotheses
- confidence_level
- compute_confidence_interval
- confidence_intervl_kind
- outputfile
- data_generation_mode (check #3)
-
