### ISSUE TITLE
The `self.scratch_dir` is invalid `Directory.SHARED_SCRATCH`

### ISSUE THREAD

**Issue by dachengx** [XENONnT/alea#221]
Because later we set `f"gsidavs://xenon-gridftp.grid.uchicago.edu:2880/xenon/scratch/{getpass.getuser()}"` as `Directory.SHARED_SCRATCH`: https://github.com/XENONnT/alea/blob/356c4b18b991e0386644a4816202df431859ab4d/alea/submitters/htcondor.py#L249, the `self.scratch_dir` in https://github.com/XENONnT/alea/blob/356c4b18b991e0386644a4816202df431859ab4d/alea/submitters/htcondor.py#L216 is never used.

**Comment by FaroutYLq** [comment]
You are right. Please feel free to remove `scratch_dir`.
