### ISSUE TITLE
Implement seeds in alea

### ISSUE THREAD

**Issue by dachengx** [XENONnT/alea#53]
Science is based on reproducibility. We should set the seed of each iteration of toy data generation. And maybe store them in toydata file or in other forms.

**Comment by hammannr** [comment]
Hmm.. Is this required? It's not so much relevant to reproduce one single toy experiment but more the collective result of a bunch of toyMC runs, which should be given anyways or not? I guess if something weird happens it is nice though and also for examples. Does it make sense to define it in the statistical_model config?

**Comment by dachengx** [comment]
This is important if one did not save the toydata, and see sth. weird a specific toy. So it should be implemented as:

1. Save the seed of each toydata(actually of each randomization), when we do or do not specify the seed
2. Give `StatisticalModel` a way to specify a seed when we debug for a toydataset

Usually, we do not specify a see. This is OK and recommended, because one is likely to forget the seed is set and generate the same toydatasets. So it is helpful to save the seed of toydata. 

Even without a discussion of the details, we can not admit that we are not able to reproduce the toydata of alea. I think this is crucial, the `reproducibility`.

**Comment by dachengx** [comment]
Technical details as reference: https://stackoverflow.com/questions/32172054/how-can-i-retrieve-the-current-seed-of-numpys-random-number-generator

**Comment by kdund** [comment]
We do not rely on individual toyMCs for the correctness of our results-- we generate enough that we have some confidence that the statistical fluctuation of the toyMC method are smaller than the precision we need. Our results are reproducible even if individual toyMCs are not. 

(similarly, our nT results are reproducible even if we will never get the exact data both times!)

**Comment by kdund** [comment]
That said, this can be very useful for debugging, it is a nice thing to want, but I do not think it is a requirement for valid inference or alea1.0
