### ISSUE TITLE
Do not submit job when the `output_filename` exists.

### ISSUE THREAD

**Issue by dachengx** [XENONnT/alea#84]
For multiple reasons, a fraction of jobs can not be successfully finished. Maybe we should not submit a job when the output is already there. 

https://github.com/XENONnT/alea/blob/c8895877761b42fbec34a8d8f834ef0b1d503f61/alea/submitter.py#L358

**Comment by kdund** [comment]
Solved by #94 ?

**Comment by dachengx** [comment]
> Solved by #94 ?

Yes
